# Use official Java image
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy everything
COPY . .

# Give permission to mvnw
RUN chmod +x mvnw

# Build the app
RUN ./mvnw clean install -DskipTests

# Expose port
EXPOSE 8080

# Run the app
CMD java -jar target/backend-0.0.1-SNAPSHOT.jar