create table if not exists public.users_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  free_generations_used integer not null default 0,
  paid_generations integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.users_usage
  add column if not exists free_generations_used integer not null default 0;

alter table public.users_usage
  add column if not exists paid_generations integer not null default 0;

alter table public.users_usage
  add column if not exists created_at timestamptz not null default now();

update public.users_usage
set free_generations_used = coalesce(free_generations_used, generations_used, 0)
where free_generations_used is null
   or free_generations_used = 0;

create unique index if not exists users_usage_user_id_key
  on public.users_usage (user_id);

alter table public.users_usage enable row level security;

drop policy if exists "Users can read their own usage" on public.users_usage;
create policy "Users can read their own usage"
on public.users_usage
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own usage" on public.users_usage;
create policy "Users can insert their own usage"
on public.users_usage
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own usage" on public.users_usage;
create policy "Users can update their own usage"
on public.users_usage
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
