create table if not exists public.billing_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  razorpay_order_id text not null unique,
  razorpay_payment_id text unique,
  status text not null default 'created',
  amount integer not null,
  currency text not null default 'INR',
  topic text,
  slides integer,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create table if not exists public.generation_credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  source text not null default 'payment',
  credits integer not null default 1,
  billing_order_id bigint references public.billing_orders (id) on delete set null,
  consumed boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists generation_credits_single_order_idx
  on public.generation_credits (billing_order_id)
  where billing_order_id is not null;

alter table public.billing_orders enable row level security;
alter table public.generation_credits enable row level security;

drop policy if exists "Users can read their own billing orders" on public.billing_orders;
create policy "Users can read their own billing orders"
on public.billing_orders
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own billing orders" on public.billing_orders;
create policy "Users can insert their own billing orders"
on public.billing_orders
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own billing orders" on public.billing_orders;
create policy "Users can update their own billing orders"
on public.billing_orders
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read their own credits" on public.generation_credits;
create policy "Users can read their own credits"
on public.generation_credits
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own credits" on public.generation_credits;
create policy "Users can insert their own credits"
on public.generation_credits
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own credits" on public.generation_credits;
create policy "Users can update their own credits"
on public.generation_credits
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
